package cn.com.git.udmp.modules.tools.entity;

import java.io.Serializable;

public class KeyGenRule implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.GEN_ID
     *
     * @mbggenerated
     */
    private String genId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.BIZ_ID
     *
     * @mbggenerated
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.BIZ_NAME
     *
     * @mbggenerated
     */
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.DATE_PATTERN
     *
     * @mbggenerated
     */
    private String datePattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.RANDOM_RANGE
     *
     * @mbggenerated
     */
    private String randomRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.SEQ_RANGE
     *
     * @mbggenerated
     */
    private String seqRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.SEQ_SEGMENT
     *
     * @mbggenerated
     */
    private Short seqSegment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.INCREMENT_NUM
     *
     * @mbggenerated
     */
    private Short incrementNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.OTHER1
     *
     * @mbggenerated
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.OTHER2
     *
     * @mbggenerated
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.GEN_RULE
     *
     * @mbggenerated
     */
    private String genRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.VALID_RULE
     *
     * @mbggenerated
     */
    private String validRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_RULE.VALID_PARAM
     *
     * @mbggenerated
     */
    private String validParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.GEN_ID
     *
     * @return the value of UDMP.T_KEY_RULE.GEN_ID
     *
     * @mbggenerated
     */
    public String getGenId() {
        return genId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.GEN_ID
     *
     * @param genId the value for UDMP.T_KEY_RULE.GEN_ID
     *
     * @mbggenerated
     */
    public void setGenId(String genId) {
        this.genId = genId == null ? null : genId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.BIZ_ID
     *
     * @return the value of UDMP.T_KEY_RULE.BIZ_ID
     *
     * @mbggenerated
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.BIZ_ID
     *
     * @param bizId the value for UDMP.T_KEY_RULE.BIZ_ID
     *
     * @mbggenerated
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.BIZ_NAME
     *
     * @return the value of UDMP.T_KEY_RULE.BIZ_NAME
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.BIZ_NAME
     *
     * @param bizName the value for UDMP.T_KEY_RULE.BIZ_NAME
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.DATE_PATTERN
     *
     * @return the value of UDMP.T_KEY_RULE.DATE_PATTERN
     *
     * @mbggenerated
     */
    public String getDatePattern() {
        return datePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.DATE_PATTERN
     *
     * @param datePattern the value for UDMP.T_KEY_RULE.DATE_PATTERN
     *
     * @mbggenerated
     */
    public void setDatePattern(String datePattern) {
        this.datePattern = datePattern == null ? null : datePattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.RANDOM_RANGE
     *
     * @return the value of UDMP.T_KEY_RULE.RANDOM_RANGE
     *
     * @mbggenerated
     */
    public String getRandomRange() {
        return randomRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.RANDOM_RANGE
     *
     * @param randomRange the value for UDMP.T_KEY_RULE.RANDOM_RANGE
     *
     * @mbggenerated
     */
    public void setRandomRange(String randomRange) {
        this.randomRange = randomRange == null ? null : randomRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.SEQ_RANGE
     *
     * @return the value of UDMP.T_KEY_RULE.SEQ_RANGE
     *
     * @mbggenerated
     */
    public String getSeqRange() {
        return seqRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.SEQ_RANGE
     *
     * @param seqRange the value for UDMP.T_KEY_RULE.SEQ_RANGE
     *
     * @mbggenerated
     */
    public void setSeqRange(String seqRange) {
        this.seqRange = seqRange == null ? null : seqRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.SEQ_SEGMENT
     *
     * @return the value of UDMP.T_KEY_RULE.SEQ_SEGMENT
     *
     * @mbggenerated
     */
    public Short getSeqSegment() {
        return seqSegment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.SEQ_SEGMENT
     *
     * @param seqSegment the value for UDMP.T_KEY_RULE.SEQ_SEGMENT
     *
     * @mbggenerated
     */
    public void setSeqSegment(Short seqSegment) {
        this.seqSegment = seqSegment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.INCREMENT_NUM
     *
     * @return the value of UDMP.T_KEY_RULE.INCREMENT_NUM
     *
     * @mbggenerated
     */
    public Short getIncrementNum() {
        return incrementNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.INCREMENT_NUM
     *
     * @param incrementNum the value for UDMP.T_KEY_RULE.INCREMENT_NUM
     *
     * @mbggenerated
     */
    public void setIncrementNum(Short incrementNum) {
        this.incrementNum = incrementNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.OTHER1
     *
     * @return the value of UDMP.T_KEY_RULE.OTHER1
     *
     * @mbggenerated
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.OTHER1
     *
     * @param other1 the value for UDMP.T_KEY_RULE.OTHER1
     *
     * @mbggenerated
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.OTHER2
     *
     * @return the value of UDMP.T_KEY_RULE.OTHER2
     *
     * @mbggenerated
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.OTHER2
     *
     * @param other2 the value for UDMP.T_KEY_RULE.OTHER2
     *
     * @mbggenerated
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.GEN_RULE
     *
     * @return the value of UDMP.T_KEY_RULE.GEN_RULE
     *
     * @mbggenerated
     */
    public String getGenRule() {
        return genRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.GEN_RULE
     *
     * @param genRule the value for UDMP.T_KEY_RULE.GEN_RULE
     *
     * @mbggenerated
     */
    public void setGenRule(String genRule) {
        this.genRule = genRule == null ? null : genRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.VALID_RULE
     *
     * @return the value of UDMP.T_KEY_RULE.VALID_RULE
     *
     * @mbggenerated
     */
    public String getValidRule() {
        return validRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.VALID_RULE
     *
     * @param validRule the value for UDMP.T_KEY_RULE.VALID_RULE
     *
     * @mbggenerated
     */
    public void setValidRule(String validRule) {
        this.validRule = validRule == null ? null : validRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_RULE.VALID_PARAM
     *
     * @return the value of UDMP.T_KEY_RULE.VALID_PARAM
     *
     * @mbggenerated
     */
    public String getValidParam() {
        return validParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_RULE.VALID_PARAM
     *
     * @param validParam the value for UDMP.T_KEY_RULE.VALID_PARAM
     *
     * @mbggenerated
     */
    public void setValidParam(String validParam) {
        this.validParam = validParam == null ? null : validParam.trim();
    }
}