package cn.com.git.udmp.modules.tools.entity;

import java.io.Serializable;

public class KeyGenSeq implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_SEQ.GEN_ID
     *
     * @mbggenerated
     */
    private String genId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_KEY_SEQ.SEQ_NUM
     *
     * @mbggenerated
     */
    private String seqNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_SEQ.GEN_ID
     *
     * @return the value of UDMP.T_KEY_SEQ.GEN_ID
     *
     * @mbggenerated
     */
    public String getGenId() {
        return genId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_SEQ.GEN_ID
     *
     * @param genId the value for UDMP.T_KEY_SEQ.GEN_ID
     *
     * @mbggenerated
     */
    public void setGenId(String genId) {
        this.genId = genId == null ? null : genId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_KEY_SEQ.SEQ_NUM
     *
     * @return the value of UDMP.T_KEY_SEQ.SEQ_NUM
     *
     * @mbggenerated
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_KEY_SEQ.SEQ_NUM
     *
     * @param seqNum the value for UDMP.T_KEY_SEQ.SEQ_NUM
     *
     * @mbggenerated
     */
    public void setSeqNum(String seqNum) {
        this.seqNum = seqNum == null ? null : seqNum.trim();
    }
}