package cn.com.git.udmp.modules.tools.dao;

import cn.com.git.udmp.common.persistence.annotation.MyBatisDao;
import cn.com.git.udmp.modules.tools.entity.KeyGenSeq;

@MyBatisDao
public interface KeyGenSeqDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String genId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    int insert(KeyGenSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    int insertSelective(KeyGenSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    KeyGenSeq selectByPrimaryKey(String genId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyGenSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_SEQ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyGenSeq record);
}