package cn.com.git.udmp.modules.tools.dao;

import cn.com.git.udmp.common.persistence.annotation.MyBatisDao;
import cn.com.git.udmp.modules.tools.entity.KeyGenRule;

@MyBatisDao
public interface KeyGenRuleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String genId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    int insert(KeyGenRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    int insertSelective(KeyGenRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    KeyGenRule selectByPrimaryKey(String genId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyGenRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_KEY_RULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyGenRule record);
}