
package cn.com.git.udmp.modules.sys.entity;

public class BizTimeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.CUSTOM_ID
     *
     * @mbggenerated
     */
    private String customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.ID_TYPE
     *
     * @mbggenerated
     */
    private String idType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_ID
     *
     * @return the value of UDMP.T_BUSINESS_TIME.CUSTOM_ID
     *
     * @mbggenerated
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_ID
     *
     * @param customId the value for UDMP.T_BUSINESS_TIME.CUSTOM_ID
     *
     * @mbggenerated
     */
    public void setCustomId(String customId) {
        this.customId = customId == null ? null : customId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.ID_TYPE
     *
     * @return the value of UDMP.T_BUSINESS_TIME.ID_TYPE
     *
     * @mbggenerated
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.ID_TYPE
     *
     * @param idType the value for UDMP.T_BUSINESS_TIME.ID_TYPE
     *
     * @mbggenerated
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }
}