
package cn.com.git.udmp.modules.sys.entity;

public class BizTime extends BizTimeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.CUSTOM_TIME
     *
     * @mbggenerated
     */
    private String customTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.TIME_PATTERN
     *
     * @mbggenerated
     */
    private String timePattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.CUSTOM_TYPE
     *
     * @mbggenerated
     */
    private String customType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.IS_BATCH
     *
     * @mbggenerated
     */
    private String isBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM1
     *
     * @mbggenerated
     */
    private String otherParam1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM2
     *
     * @mbggenerated
     */
    private String otherParam2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_BUSINESS_TIME.DEL_FLAG
     *
     * @mbggenerated
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_TIME
     *
     * @return the value of UDMP.T_BUSINESS_TIME.CUSTOM_TIME
     *
     * @mbggenerated
     */
    public String getCustomTime() {
        return customTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_TIME
     *
     * @param customTime the value for UDMP.T_BUSINESS_TIME.CUSTOM_TIME
     *
     * @mbggenerated
     */
    public void setCustomTime(String customTime) {
        this.customTime = customTime == null ? null : customTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.TIME_PATTERN
     *
     * @return the value of UDMP.T_BUSINESS_TIME.TIME_PATTERN
     *
     * @mbggenerated
     */
    public String getTimePattern() {
        return timePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.TIME_PATTERN
     *
     * @param timePattern the value for UDMP.T_BUSINESS_TIME.TIME_PATTERN
     *
     * @mbggenerated
     */
    public void setTimePattern(String timePattern) {
        this.timePattern = timePattern == null ? null : timePattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_TYPE
     *
     * @return the value of UDMP.T_BUSINESS_TIME.CUSTOM_TYPE
     *
     * @mbggenerated
     */
    public String getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.CUSTOM_TYPE
     *
     * @param customType the value for UDMP.T_BUSINESS_TIME.CUSTOM_TYPE
     *
     * @mbggenerated
     */
    public void setCustomType(String customType) {
        this.customType = customType == null ? null : customType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.IS_BATCH
     *
     * @return the value of UDMP.T_BUSINESS_TIME.IS_BATCH
     *
     * @mbggenerated
     */
    public String getIsBatch() {
        return isBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.IS_BATCH
     *
     * @param isBatch the value for UDMP.T_BUSINESS_TIME.IS_BATCH
     *
     * @mbggenerated
     */
    public void setIsBatch(String isBatch) {
        this.isBatch = isBatch == null ? null : isBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM1
     *
     * @return the value of UDMP.T_BUSINESS_TIME.OTHER_PARAM1
     *
     * @mbggenerated
     */
    public String getOtherParam1() {
        return otherParam1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM1
     *
     * @param otherParam1 the value for UDMP.T_BUSINESS_TIME.OTHER_PARAM1
     *
     * @mbggenerated
     */
    public void setOtherParam1(String otherParam1) {
        this.otherParam1 = otherParam1 == null ? null : otherParam1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM2
     *
     * @return the value of UDMP.T_BUSINESS_TIME.OTHER_PARAM2
     *
     * @mbggenerated
     */
    public String getOtherParam2() {
        return otherParam2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.OTHER_PARAM2
     *
     * @param otherParam2 the value for UDMP.T_BUSINESS_TIME.OTHER_PARAM2
     *
     * @mbggenerated
     */
    public void setOtherParam2(String otherParam2) {
        this.otherParam2 = otherParam2 == null ? null : otherParam2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_BUSINESS_TIME.DEL_FLAG
     *
     * @return the value of UDMP.T_BUSINESS_TIME.DEL_FLAG
     *
     * @mbggenerated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_BUSINESS_TIME.DEL_FLAG
     *
     * @param delFlag the value for UDMP.T_BUSINESS_TIME.DEL_FLAG
     *
     * @mbggenerated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }
}