package cn.com.git.udmp.calc.modules.demo.entity;

import java.util.Date;

import cn.com.git.udmp.calc.modules.demo.entity.base.BaseEntity;

public class BatchTestSouce extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.NUM_A
     *
     * @mbggenerated
     */
    private Long numA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CHAR_B
     *
     * @mbggenerated
     */
    private String charB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.VCHAR_C
     *
     * @mbggenerated
     */
    private String vcharC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CLOB_D
     *
     * @mbggenerated
     */
    private Date clobD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_BY
     *
     * @mbggenerated
     */
    private Long insertBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIME
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date insertTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_BY
     *
     * @mbggenerated
     */
    private Long updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.NUM_A
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.NUM_A
     *
     * @mbggenerated
     */
    public Long getNumA() {
        return numA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.NUM_A
     *
     * @param numA the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.NUM_A
     *
     * @mbggenerated
     */
    public void setNumA(Long numA) {
        this.numA = numA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CHAR_B
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.CHAR_B
     *
     * @mbggenerated
     */
    public String getCharB() {
        return charB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CHAR_B
     *
     * @param charB the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.CHAR_B
     *
     * @mbggenerated
     */
    public void setCharB(String charB) {
        this.charB = charB == null ? null : charB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.VCHAR_C
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.VCHAR_C
     *
     * @mbggenerated
     */
    public String getVcharC() {
        return vcharC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.VCHAR_C
     *
     * @param vcharC the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.VCHAR_C
     *
     * @mbggenerated
     */
    public void setVcharC(String vcharC) {
        this.vcharC = vcharC == null ? null : vcharC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CLOB_D
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.CLOB_D
     *
     * @mbggenerated
     */
    public Date getClobD() {
        return clobD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.CLOB_D
     *
     * @param clobD the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.CLOB_D
     *
     * @mbggenerated
     */
    public void setClobD(Date clobD) {
        this.clobD = clobD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_BY
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_BY
     *
     * @mbggenerated
     */
    public Long getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_BY
     *
     * @param insertBy the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_BY
     *
     * @mbggenerated
     */
    public void setInsertBy(Long insertBy) {
        this.insertBy = insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIME
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIME
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIME
     *
     * @param insertTime the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIME
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIMESTAMP
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getInsertTimestamp() {
        return insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIMESTAMP
     *
     * @param insertTimestamp the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.INSERT_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setInsertTimestamp(Date insertTimestamp) {
        this.insertTimestamp = insertTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_BY
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_BY
     *
     * @mbggenerated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_BY
     *
     * @param updateBy the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_BY
     *
     * @mbggenerated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIME
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIME
     *
     * @param updateTime the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIMESTAMP
     *
     * @return the value of UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for UDMP.T_UDMP_BATCH_TEST_SOURCE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}