package cn.com.git.udmp.calc.modules.demo.dao;

import org.apache.ibatis.annotations.Mapper;

import cn.com.git.udmp.calc.modules.demo.entity.BatchTestDest;

@Mapper
public interface BatchTestDestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long numA);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    int insert(BatchTestDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    int insertSelective(BatchTestDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    BatchTestDest selectByPrimaryKey(Long numA);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BatchTestDest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UDMP.T_UDMP_BATCH_TEST_DEST
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BatchTestDest record);
}